openapi: 3.0.1
info:
  title: MITRE ATT&CK TAXII API Wrapper
  version: "1.0.0"
  description: >
    Retrieves Enterprise ATT&CK STIX objects from MITRE’s TAXII 2.1 server.

servers:
  - url: https://cti-taxii.mitre.org/stix

paths:
  /collections/{collectionId}/objects/:
    get:
      summary: Get Enterprise ATT&CK STIX objects
      description: >
        Retrieves the full STIX object bundle for the specified MITRE ATT&CK collection.
      parameters:
        - name: collectionId
          in: path
          required: true
          description: MITRE Enterprise ATT&CK collection UUID.
          schema:
            type: string
            example: "95ecc380-afe9-11e4-9b6c-751b66dd541e"
      responses:
        '200':
          description: Successfully retrieved MITRE ATT&CK STIX objects.
          content:
            application/json:
              schema:
                type: object
